events {}

http {
    upstream grpc_backend {
        server server1:50051;
        server server2:50051;
        server server3:50051;
    }

    server {
        listen 8080 http2;

        location / {
            grpc_pass grpc://grpc_backend;

            grpc_set_header Host $host;
            grpc_set_header X-Real-IP $remote_addr;
            grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}